### ISSUE TITLE
Numbering

### ISSUE THREAD

**Issue by ljupchokanevche** [LyndaSub/LyndaSub#27]
Could it be possible to add double digits on the folders and the introductions folder to start with 00. 
and conclusion with the last number

**Comment by theshem** [comment]
@kanevsr Yes it is, but since not all courses have < 100 chapters, I ended up with leaving chapter titles as-is in website. For instance this [on-going course](http://www.lynda.com/Illustrator-tutorials/Dekes-Techniques/76067-2.html) has different naming for chapters.

Any ideas? Please let me know.

**Comment by StanislavMayorov** [comment]
@HashemQolami 
I think that numbering is good idea. There are not course with 100 chapters now.  if course have 100+ chapter then it may have different numbering or chapter titles as-is in website.

**Comment by StanislavMayorov** [comment]
I noticed that some courses have introduction chapter with number.
http://www.lynda.com/3D-Animation-Games-tutorials/Unity-43-Essential-Training/150613-2.html

**Comment by theshem** [comment]
@kanevsr Added back the numbering. Fixed weekly courses as well #28
